// Code generated by xgo (XGo); DO NOT EDIT.

package hrefs

import (
	"github.com/goplus/xgo/dql/fetcher"
	"github.com/goplus/xgo/dql/html"
)

const XGoPackage = "github.com/goplus/xgo/dql/html"
const _ = true
// Result represents the result of hrefs fetcher.
type Result struct {
	URL   string   `json:"url,omitempty"`
	Hrefs []string `json:"hrefs,omitempty"`
}
//line dql/fetcher/hrefs/hrefs.xgo:30:1
// New extracts hrefs from the given document and returns the Result.
func New(input interface{}, doc html.NodeSet) Result {
//line dql/fetcher/hrefs/hrefs.xgo:32:1
	hrefs := func() (_xgo_ret []string) {
		for
//line dql/fetcher/hrefs/hrefs.xgo:32:1
		a := range doc.XGo_Any("a").XGo_Enum() {
//line dql/fetcher/hrefs/hrefs.xgo:32:1
			if
//line dql/fetcher/hrefs/hrefs.xgo:32:1
			url := a.XGo_Attr__0("href"); url != "" {
//line dql/fetcher/hrefs/hrefs.xgo:32:1
				_xgo_ret = append(_xgo_ret, url)
			}
		}
//line dql/fetcher/hrefs/hrefs.xgo:32:1
		return
	}()
//line dql/fetcher/hrefs/hrefs.xgo:33:1
	return Result{input.(string), hrefs}
}
//line dql/fetcher/hrefs/hrefs.xgo:36:1
// URL returns the URL from the input.
// Input is expected to be a URL, and the fetcher will extract all hrefs
// from the page at that URL.
func URL(input interface{}) string {
//line dql/fetcher/hrefs/hrefs.xgo:40:1
	return input.(string)
}
//line dql/fetcher/hrefs/hrefs.xgo:43:1
func init() {
//line dql/fetcher/hrefs/hrefs.xgo:44:1
	fetcher.Register("hrefs", New, URL)
}
