// Code generated by xgo (XGo); DO NOT EDIT.

package repoList

import (
	"github.com/goplus/xgo/dql/fetcher"
	"github.com/goplus/xgo/dql/html"
	"strings"
)

const XGoPackage = "github.com/goplus/xgo/dql/html"
const _ = true
// Repo is the information of a repository.
type Repo struct {
	Repo       string `json:"repo"`
	ForkedFrom string `json:"forkedFrom"`
	Title      string `json:"title"`
	Language   string `json:"language"`
	UpdateTime string `json:"updateTime"`
	Forks      int    `json:"forks"`
}
// Result is the result of fetching a repository list page.
type Result struct {
	User  string `json:"user"`
	Repos []Repo `json:"repos"`
	Next  string `json:"next"`
}
//line dql/fetcher/github.com/repoList/repoList.xgo:41:1
func newRepo(node html.NodeSet) Repo {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
	aRepo := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
		node.XGo_Any("a").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
			if self.XGo_Attr__0("itemprop") == "name codeRepository" {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:42:1
			return true
		})
	}).One()
//line dql/fetcher/github.com/repoList/repoList.xgo:43:1
	repo := aRepo.XGo_Attr__0("href")
//line dql/fetcher/github.com/repoList/repoList.xgo:44:1
	root := aRepo.ParentN(3).One()
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
	forkedFrom := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
		root.XGo_Any("span").XGo_Any("textNode").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
			if strings.TrimSpace(self.Value__0()) == "Forked from" {
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:45:1
			return true
		})
	}).NextSibling().XGo_Select("a").XGo_Attr__0("href")
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
	title := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
		root.XGo_Any("p").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
			if self.XGo_Attr__0("itemprop") == "description" {
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:46:1
			return true
		})
	}).Text__0()
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
	language := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
		root.XGo_Any("span").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
			if self.XGo_Attr__0("itemprop") == "programmingLanguage" {
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:47:1
			return true
		})
	}).Text__0()
//line dql/fetcher/github.com/repoList/repoList.xgo:48:1
	updateTime := root.XGo_Any("relative-time").XGo_Attr__0("datetime")
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
	forks := func() (_xgo_ret int) {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
		var _xgo_err error
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
		_xgo_ret, _xgo_err = html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
			root.XGo_Any("a").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
				if self.XGo_Attr__0("href") == repo+"/network/members" {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
					if
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
					_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
						if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
							return false
						}
					}
				}
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
				return true
			})
		}).Int()
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
		if _xgo_err != nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
			return 0
		}
//line dql/fetcher/github.com/repoList/repoList.xgo:49:1
		return
	}()
//line dql/fetcher/github.com/repoList/repoList.xgo:50:1
	return Repo{Repo: repo, ForkedFrom: forkedFrom, Title: title, Language: language, UpdateTime: updateTime, Forks: forks}
}
//line dql/fetcher/github.com/repoList/repoList.xgo:60:1
// New extracts the repository information from the given HTML document and
// returns the Result.
func New(input interface{}, doc html.NodeSet) Result {
//line dql/fetcher/github.com/repoList/repoList.xgo:63:1
	user := input.(string)
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
	divRepos := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
		doc.XGo_Any("div").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
			if self.XGo_Attr__0("id") == "user-repositories-list" {
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:64:1
			return true
		})
	}).One()
//line dql/fetcher/github.com/repoList/repoList.xgo:65:1
	repos := func() (_xgo_ret []Repo) {
		for
//line dql/fetcher/github.com/repoList/repoList.xgo:65:1
		x := range divRepos.XGo_Elem("ul").XGo_Elem("li").XGo_Enum() {
//line dql/fetcher/github.com/repoList/repoList.xgo:65:1
			_xgo_ret = append(_xgo_ret, newRepo(x))
		}
//line dql/fetcher/github.com/repoList/repoList.xgo:65:1
		return
	}()
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
	divPaginate := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
		doc.XGo_Any("div").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
			if self.IsClass("paginate-container") {
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:66:1
			return true
		})
	}).One()
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
	next := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
		divPaginate.XGo_Any("a").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
			if self.Text__0() == "Next" {
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
				if
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/repoList/repoList.xgo:67:1
			return true
		})
	}).XGo_Attr__0("href")
//line dql/fetcher/github.com/repoList/repoList.xgo:68:1
	return Result{user, repos, next}
}
//line dql/fetcher/github.com/repoList/repoList.xgo:71:1
// URL returns the URL from the input.
// Input is expected to be a GitHub username, and the URL will be the user's
// repository list page.
func URL(input interface{}) string {
//line dql/fetcher/github.com/repoList/repoList.xgo:75:1
	return "https://github.com/" + input.(string)
}
//line dql/fetcher/github.com/repoList/repoList.xgo:78:1
func init() {
//line dql/fetcher/github.com/repoList/repoList.xgo:79:1
	fetcher.Register("github.com/repoList", New, URL)
}
