// Code generated by xgo (XGo); DO NOT EDIT.

package importedBy

import (
	"github.com/goplus/xgo/dql"
	"github.com/goplus/xgo/dql/fetcher"
	"github.com/goplus/xgo/dql/html"
	"github.com/qiniu/x/errors"
	"strings"
)

const XGoPackage = "github.com/goplus/xgo/dql/html"
const _ = true

type Result struct {
	Path       string `json:"path"`
	ImportedBy int    `json:"importedBy"`
}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:30:1
// New extracts the number of packages that import the given package from
// the given HTML document and returns the Result.
func New(input interface{}, doc html.NodeSet) Result {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:33:1
	const importedBy = "Imported By:"
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:34:1
	path := input.(string)
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
	a := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
		doc.XGo_Any("a").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
			if strings.HasPrefix(func() (_xgo_ret string) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				var _xgo_err error
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				_xgo_ret, _xgo_err = self.XGo_Attr__1("aria-label")
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				if _xgo_err != nil {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
					return ""
				}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				return
			}(), importedBy) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				if
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
						return false
					}
				}
			}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:35:1
			return true
		})
	}).One()
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:36:1
	if !a.Ok() {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:37:1
		return Result{path, 0}
	}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
	label := func() (_xgo_ret string) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
		var _xgo_err error
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
		_xgo_ret, _xgo_err = a.XGo_Attr__1("aria-label")
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
		if _xgo_err != nil {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
			_xgo_err = errors.NewFrame(_xgo_err, "a.$\"aria-label\"", "dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo", 39, "importedBy.New")
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
			panic(_xgo_err)
		}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:39:1
		return
	}()
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
	nImported := func() (_xgo_ret int) {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
		var _xgo_err error
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
		_xgo_ret, _xgo_err = dql.Int(label[len(importedBy):])
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
		if _xgo_err != nil {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
			_xgo_err = errors.NewFrame(_xgo_err, "dql.int(label[len(importedBy):])", "dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo", 40, "importedBy.New")
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
			panic(_xgo_err)
		}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:40:1
		return
	}()
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:42:1
	return Result{path, nImported}
}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:45:1
// URL returns the input URL for the given input.
// Input is expected to be a Go package path.
func URL(input interface{}) string {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:48:1
	return "https://pkg.go.dev/" + input.(string)
}
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:51:1
func init() {
//line dql/fetcher/pkg.go.dev/importedBy/importedBy.xgo:52:1
	fetcher.Register("pkg.go.dev/importedBy", New, URL)
}
