// Code generated by xgo (XGo); DO NOT EDIT.

package fndoc

import (
	"github.com/goplus/xgo/dql/fetcher"
	"github.com/goplus/xgo/dql/html"
	"strings"
)

const XGoPackage = "github.com/goplus/xgo/dql/html"
const _ = true
const spaces = " \t\r\n¶"

type Result struct {
	Name string `json:"name"`
	Type string `json:"type,omitempty"`
	Doc  string `json:"doc,omitempty"`
	Sig  string `json:"sig"`
	URL  string `json:"url,omitempty"`
}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:38:1
// New extracts the function declaration from the given HTML document
// and returns the Result.
func New(input interface{}, doc html.NodeSet) Result {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:41:1
	name := input.(string)
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:42:1
	url := name
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:43:1
	if name != "" {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:62:1
		url = URL(input)
	}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:46:1
	if doc.Ok() {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
		fn := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
			doc.XGo_Any("dl").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
				if self.IsClass("py function") {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
					if
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
					_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
						if !_xgo_yield(_xgo_val) {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
							return false
						}
					}
				}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:47:1
				return true
			})
		}).One()
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:48:1
		decl := fn.FirstElementChild().XGo_Select("dt").Text__0()
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:49:1
		pos := strings.IndexByte(decl, '(')
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:50:1
		if pos > 0 {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:51:1
			sig := decl[pos:]
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:52:1
			return Result{name, "function", "", strings.TrimRight(sig, spaces), url}
		}
	}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:55:1
	return Result{name, "", "", "<NULL>", url}
}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:58:1
// URL returns the input URL for the given input.
// Input is expected to be a function name, and the URL will be the function's
// documentation page on pytorch.org.
func URL(input interface{}) string {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:62:1
	return "https://pytorch.org/docs/stable/generated/torch." + input.(string) + ".html"
}
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:65:1
func init() {
//line dql/fetcher/pytorch.org/fndoc/fndoc.xgo:66:1
	fetcher.Register("pytorch.org/fndoc", New, URL)
}
