// Code generated by xgo (XGo); DO NOT EDIT.

package issueTask

import (
	"github.com/goplus/xgo/dql/fetcher"
	"github.com/goplus/xgo/dql/html"
	"strings"
)

const XGoPackage = "github.com/goplus/xgo/dql/html"
const _ = true
// Task represents a GitHub issue task item.
type Task struct {
	Desc string `json:"desc"`
	Done bool   `json:"done"`
}
// Result represents the result of issue task fetcher.
type Result struct {
	Issue string `json:"issue"`
	Tasks []Task `json:"tasks"`
}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:36:1
// New extracts issue tasks from the given document and returns the Result.
func New(input interface{}, doc html.NodeSet) Result {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:38:1
	issue := input.(string)
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
	taskList := html.NodeSet_Cast(func(_xgo_yield func(*html.Node) bool) {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
		doc.XGo_Any("ul").XGo_Enum()(func(self html.NodeSet) bool {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
			if self.IsClass("contains-task-list") {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
				if
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
					if !_xgo_yield(_xgo_val) {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
						return false
					}
				}
			}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:39:1
			return true
		})
	}).One()
//line dql/fetcher/github.com/issueTask/issueTask.xgo:40:1
	tasks := func() (_xgo_ret []Task) {
		for
//line dql/fetcher/github.com/issueTask/issueTask.xgo:40:1
		li := range taskList.XGo_Elem("li").XGo_Enum() {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:40:1
			_xgo_ret = append(_xgo_ret, Task{li.Text__0(), li.FirstElementChild().HasAttr("checked")})
		}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:40:1
		return
	}()
//line dql/fetcher/github.com/issueTask/issueTask.xgo:41:1
	return Result{issue, tasks}
}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:44:1
// URL returns the URL from the input.
// Input can be either a full github issue URL or a shorthand format
// like "goplus/llgo#642".
func URL(input interface{}) string {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:48:1
	issue := input.(string)
//line dql/fetcher/github.com/issueTask/issueTask.xgo:49:1
	if strings.HasPrefix(issue, "https://github.com/") {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:50:1
		return issue
	}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:52:1
	return "https://github.com/" + strings.Replace(issue, "#", "/issues/", 1)
}
//line dql/fetcher/github.com/issueTask/issueTask.xgo:55:1
func init() {
//line dql/fetcher/github.com/issueTask/issueTask.xgo:56:1
	fetcher.Register("github.com/issueTask", New, URL)
}
